# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod download
builds:
  - main: main.go
    binary: boring-registry
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    ldflags:
      - -s -w -X github.com/TierMobility/boring-registry/version.Version={{.Version}} -X github.com/TierMobility/boring-registry/version.Commit={{.Commit}} -X github.com/TierMobility/boring-registry/version.Date={{.Date}} -X github.com/TierMobility/boring-registry/version.BuiltBy=goreleaser
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
